### ISSUE TITLE
Improvement In Documation

### ISSUE THREAD

**Issue by JeelDobariya38** [JeelDobariya38/pyfilehandling#4]
## Upgrade a documation for `v1.1.1` release code

**Comment by AdityaPrasad275** [comment]
I just copy pasted text/code from the webpage linked in your readme. This is how it look raw. Do you want to add more information or ig better frame it, word it better?

[readme.md](https://github.com/JeelDobariya38/pyfilehandling/files/11713105/readme.md)

**Comment by JeelDobariya38** [comment]
# Great Work!!!
Thanks for your contribution,

# Request
Can you please do this:-
- clone this repository 
- submit a pull request describe your change so that i can merge it in my repository

**Comment by JeelDobariya38** [comment]
successful closed by Pull Request #5
all thanks to AdityaPrasad275 for add a good documation
